# Generated by Django 3.1.5 on 2021-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instock',
            field=models.IntegerField(default=100),
        ),
    ]
